import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NavBar } from "./Nav/NavBar";
import RightSideBar from "./RightSideBar/RightSideBar";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <div className="flex flex-col h-full min-h-screen 2xl:flex-row bg-gradient-to-b from-gray-950 to-gray-900">
                    <aside className="order-1 w-full md:w-64 md:order-none">
                        <NavBar />
                    </aside>

                    <main className="justify-center order-2 md:order-none">
                        <div className="flex justify-center max-w-3xl">
                            {children}
                        </div>
                    </main>
                    <aside className="order-3 w-full md:w-64 md:order-none">
                        <RightSideBar />
                    </aside>
                </div>
            </body>
        </html>
    );
}
